// Top-level build file to bridge the Android project into the IDE root

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.1'
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

// Apply common variables from the android folder
apply from: "android/variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
